import { Store, Stop, Student, today } from "./trip";
export const stops: Stop[] = [
  {
    id: "s1",
    name: "망원역 2번 출구",
    time: "14:00",
    address: "마포구 월드컵로 77",
    x: 215,
    y: 320,
  },
  {
    id: "s2",
    name: "성산 어린이공원",
    time: "14:07",
    address: "마포구 성산로4길 15",
    x: 325,
    y: 243,
  },
  {
    id: "s3",
    name: "드림빌 아파트",
    time: "14:15",
    address: "마포구 월드컵로25길 32",
    x: 455,
    y: 190,
  },
  {
    id: "s4",
    name: "망원초등학교 정문",
    time: "14:22",
    address: "마포구 방울내로5길 28",
    x: 345,
    y: 105,
  },
  {
    id: "s5",
    name: "리틀스텝 체육센터",
    time: "14:30",
    address: "마포구 월드컵로 180",
    x: 555,
    y: 65,
  },
];
export const students: Student[] = [
  {
    id: "c1",
    name: "김민준",
    className: "유아체육 1반",
    stopId: "s1",
    guardian: "김지현",
  },
  {
    id: "c2",
    name: "최지우",
    className: "유아체육 1반",
    stopId: "s1",
    guardian: "최유진",
  },
  {
    id: "c3",
    name: "정하준",
    className: "유아체육 1반",
    stopId: "s2",
    guardian: "정수연",
  },
  {
    id: "c4",
    name: "이서아",
    className: "유아체육 1반",
    stopId: "s3",
    guardian: "이수진",
  },
  {
    id: "c5",
    name: "윤서준",
    className: "유아체육 1반",
    stopId: "s3",
    guardian: "윤지영",
  },
  {
    id: "c6",
    name: "박도윤",
    className: "유아체육 1반",
    stopId: "s4",
    guardian: "박현우",
  },
  {
    id: "c7",
    name: "한지안",
    className: "유아체육 1반",
    stopId: "s4",
    guardian: "한서연",
  },
  {
    id: "c8",
    name: "강하린",
    className: "유아체육 1반",
    stopId: "s4",
    guardian: "강민지",
  },
];
export function seed(): Store {
  const date = today();
  const at = (v: string) => `${date}T${v}:00+09:00`;
  return {
    version: 1,
    organization: "리틀스텝 체육센터",
    notifications: true,
    template: structuredClone(stops),
    students: structuredClone(students),
    trip: {
      id: "demo-" + date,
      date,
      status: "RUNNING",
      phase: "MOVING",
      current: 2,
      stops: structuredClone(stops),
      states: {
        c1: "BOARDED",
        c2: "BOARDED",
        c3: "BOARDED",
        c4: "WAITING",
        c5: "WAITING",
        c6: "WAITING",
        c7: "ABSENT",
        c8: "WAITING",
      },
      assignments: Object.fromEntries(students.map((c) => [c.id, c.stopId])),
      delay: 2,
      gps: "DEMO",
      updatedAt: at("14:10"),
      requests: [
        {
          id: "r1",
          studentId: "c6",
          kind: "STOP_CHANGE",
          detail: "오늘은 드림빌 아파트에서 탑승하고 싶어요.",
          stopId: "s3",
          status: "SUBMITTED",
          createdAt: at("14:09"),
        },
        {
          id: "r2",
          studentId: "c7",
          kind: "ABSENT",
          detail: "오늘은 결석합니다.",
          status: "APPLIED",
          createdAt: at("13:40"),
        },
      ],
      events: [
        {
          id: "e5",
          type: "REQUEST_SUBMITTED",
          message: "박도윤 · 탑승 장소 변경 요청",
          actor: "학부모",
          studentId: "c6",
          time: at("14:09"),
        },
        {
          id: "e4",
          type: "STOP_DEPARTED",
          message: "성산 어린이공원에서 출발했습니다.",
          actor: "운전자",
          time: at("14:08"),
        },
        {
          id: "e3",
          type: "STUDENT_BOARDED",
          message: "정하준 · 탑승 완료",
          actor: "운전자",
          studentId: "c3",
          time: at("14:07"),
        },
        {
          id: "e2",
          type: "STUDENT_BOARDED",
          message: "김민준 · 탑승 완료",
          actor: "운전자",
          studentId: "c1",
          time: at("14:01"),
        },
        {
          id: "e1",
          type: "TRIP_STARTED",
          message: "셔틀 운행을 시작했습니다.",
          actor: "운전자",
          time: at("14:00"),
        },
      ],
    },
  };
}
